// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dahbxzagpoxqgseajctf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhaGJ4emFncG94cWdzZWFqY3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTk3MjksImV4cCI6MjA2OTg5NTcyOX0.S2sL8cFQvT0uVfCQfs0rIAQmUNgmF7hImUuw-KQgBUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});